Workshop5.Rev2.App/Controllers/PackageController.cs
using System.Linq;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Workshop5.Rev2.BLL;
using Workshop5.Rev2.App.Models;
using Workshop5.Rev2.Data.Domain;

namespace Workshop5.Rev2.App.Controllers
{ /*Package Controller is coded by Larisa Steig*/
    public class PackageController : Controller
    {
        // GET: PackageController
        public ActionResult Index()
        {
            var packages = PackageManager.GetAll();
            return View(packages);
        }

        // GET: PackageController/Details/5

        public ActionResult Details()
        {
            var packages = PackageManager.GetAll();
            return View(packages);
        }
        public ActionResult Data(int id)

        {
            var packages = PackageManager.GetAll();
            var package = packages.SingleOrDefault(m => m.PackageId == id);
            return PartialView("_PackageDetails", package);

        }


        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Packages package)
        {
            try
            {
                //call the OwnerManager to add
                PackageManager.Add(package);

                return RedirectToAction(nameof(Details));
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Edit(int id)
        {
            var package = PackageManager.Find(id);
            return View(package);
        }

        [HttpPost]
        public ActionResult Edit(Packages package)
        {
            try
            {
                //call the OwnerManager to add
                PackageManager.update(package);

                return RedirectToAction(nameof(Details));
            }
            catch
            {
                return View();
            }
        }


        public IActionResult PackageDetail()
        {
            return View();
        }
    }
}

Workshop5.Rev2.App/Views/Shared/_Layout.cshtml
@*Original Navbar coded by David Hahner*@
@*modified by group 3*@

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Travel Experts </title>
    <link href="~/Photos/icon.jpeg" rel="shortcut icon" type="image/x-icon" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet"
          href="https://use.fontawesome.com/releases/v5.7.0/css/all.css"
          integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ"
          crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-inverse fixed-top">
            <div class="navbar-header">
                <a href="@Url.Action("Index", "HOME")" class="navbar-brand">
                    <img id="logo" src="~/Photos/logo-wht-bg.jpg" title="core" alt="" class="navbar-left"/>
                </a>
            </div>
                <button class="navbar-toggler" type="button" data-toggle="collapse"
                        data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                     <span class="navbar-toggler-icon text-light">
                    <i class="fas fa-bars" style="color: #fff; font-size: 28px;"></i>
                </span>
                @*<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Travel Experts Logo?</a>*@
            </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item active">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (User.Identity.Name == null && !User.Identity.IsAuthenticated)
                        {
                    <li class="nav-item active">
                        <a class="nav-link text-light" asp-area="" asp-controller="Account" asp-action="Create">Register</a>
                    </li>
                                    <li class="nav-item active">
                                        <a class="nav-link text-light" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                                    </li> }
                                                else if (User.Identity.Name == null && User.Identity.IsAuthenticated)
                                                {
                                    <li class="nav-item active">
                                        <a class="nav-link text-light" asp-area="" asp-controller="Account" asp-action="Logout">Logout</a>
                                    </li>
                                                    <li class="nav-item active">
                                                        <a class="nav-link text-light" asp-area="" asp-controller="Package" asp-action="Details">Packages</a>
                                                    </li>
                                                    

                        }

                        else
                        {
                        <li class="nav-item active">
                            <a class="nav-link text-light" asp-area="" asp-controller="Account" asp-action="Edit">Update Registration</a>
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link text-light" asp-area="" asp-controller="Account" asp-action="Logout">Logout</a>
                        </li>
                        }

                    </ul>
                   
               
                    @if (!User.Identity.IsAuthenticated)
                    {
                    <span id="uxWelcome" runat="server" class="navbar-text"></span>
                    <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link text-light" runat="server"
                           href="~/Agent/Login" title="Agent Page">
                            <span class="fa fa-users"></span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-light" runat="server"
                           href="~/Account/Create" title="Register">
                            <span class="fa fa-user"></span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-light" runat="server"
                           href="~/Account/Login" title="Login">
                            <span class="fa fa-sign-in-alt"></span>
                        </a>
                    </li>
                </ul>}
                    @if (User.Identity.IsAuthenticated)
                    {
                      <span id="uxWelcome" runat="server" class="navbar-text">Welcome @User.Identity.Name!</span>
                        <ul class="navbar-nav rm">
                            <li class="nav-item">
                                <a class="nav-link text-light" runat="server"
                                   href="~/Account/Logout" title="Logout">
                                  <span class="fa fa-sign-out-alt"></span>
                                </a>
                             </li>
                        </ul>
                     }
                </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="border-top footer text-light">
        <div class="container">
            &copy; 2020 Travel Experts   
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>